import type { ProviderPreset } from "../../shared/ipc";
import { enrichModelEntry } from "../../shared/model-context";

export function listProviderPresets(): ProviderPreset[] {
  return rawProviderPresets().map((preset) => ({
    ...preset,
    models: preset.models.map((m) => enrichModelEntry(m)),
  }));
}

function rawProviderPresets(): ProviderPreset[] {
  return [
    // —— 国内官方 / 主流 ——
    {
      id: "deepseek",
      name: "DeepSeek",
      // 必须与 deepseek-anthropic 使用不同 providerId。
      // Pi auth/models.json 的键空间就是 providerId，没有 api 维度 namespace；
      // 若两者共用 providerId，激活其中一个会覆盖另一个的 key。
      providerId: "deepseek",
      api: "openai-completions",
      baseUrl: "https://api.deepseek.com",
      models: [
        { id: "deepseek-chat", name: "DeepSeek Chat" },
        { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
        { id: "deepseek-reasoner", name: "DeepSeek Reasoner" },
      ],
      notes: "DeepSeek OpenAI-compatible（参考 cc-switch）",
      category: "cn",
      websiteUrl: "https://platform.deepseek.com",
    },
    {
      id: "deepseek-anthropic",
      name: "DeepSeek (Anthropic)",
      // 与 openai-completions 预设解耦的独立 providerId，
      // 避免激活 deepseek-anthropic 时覆盖 Pi 中的 deepseek OpenAI key。
      providerId: "deepseek-anthropic",
      api: "anthropic-messages",
      baseUrl: "https://api.deepseek.com/anthropic",
      models: [
        { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
        { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
      ],
      notes: "DeepSeek Anthropic 兼容层",
      category: "cn",
      websiteUrl: "https://platform.deepseek.com",
    },
    {
      id: "kimi",
      name: "Kimi",
      providerId: "kimi",
      api: "anthropic-messages",
      baseUrl: "https://api.moonshot.cn/anthropic",
      models: [{ id: "kimi-k2.7-code", name: "Kimi K2.7 Code" }],
      notes: "月之暗面 Kimi Anthropic 兼容",
      category: "cn",
      websiteUrl: "https://platform.moonshot.cn",
    },
    {
      id: "kimi-coding",
      name: "Kimi For Coding",
      providerId: "kimi",
      api: "anthropic-messages",
      baseUrl: "https://api.kimi.com/coding/",
      models: [{ id: "kimi-for-coding", name: "Kimi For Coding" }],
      notes: "Kimi 编程专用端点",
      category: "cn",
      websiteUrl: "https://www.kimi.com/code",
    },
    {
      id: "zhipu",
      name: "智谱 GLM",
      providerId: "zhipu",
      api: "anthropic-messages",
      baseUrl: "https://open.bigmodel.cn/api/anthropic",
      models: [{ id: "glm-5.1", name: "GLM-5.1" }],
      notes: "智谱 BigModel Anthropic 兼容",
      category: "cn",
      websiteUrl: "https://open.bigmodel.cn",
    },
    {
      id: "zhipu-en",
      name: "智谱 GLM (国际)",
      providerId: "zhipu",
      api: "anthropic-messages",
      baseUrl: "https://api.z.ai/api/anthropic",
      models: [{ id: "glm-5.1", name: "GLM-5.1" }],
      notes: "Z.ai 国际站",
      category: "cn",
      websiteUrl: "https://z.ai",
    },
    {
      id: "bailian",
      name: "阿里云百炼",
      providerId: "bailian",
      api: "anthropic-messages",
      baseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
      models: [{ id: "qwen-plus", name: "Qwen Plus" }],
      notes: "DashScope Anthropic 兼容",
      category: "cn",
      websiteUrl: "https://bailian.console.aliyun.com",
    },
    {
      id: "bailian-coding",
      name: "百炼 Coding",
      providerId: "bailian",
      api: "anthropic-messages",
      baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
      models: [{ id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" }],
      notes: "百炼编程专用端点",
      category: "cn",
      websiteUrl: "https://bailian.console.aliyun.com",
    },
    {
      id: "minimax",
      name: "MiniMax",
      providerId: "minimax",
      api: "anthropic-messages",
      baseUrl: "https://api.minimaxi.com/anthropic",
      models: [
        { id: "MiniMax-M3", name: "MiniMax M3" },
        { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
        { id: "MiniMax-M2.7-highspeed", name: "MiniMax M2.7 Highspeed" },
      ],
      notes: "MiniMax 国内 Anthropic 兼容;M3 支持思考开关,M2.7 始终 thinking。",
      category: "cn",
      websiteUrl: "https://platform.minimaxi.com",
    },
    {
      id: "minimax-en",
      name: "MiniMax (国际)",
      providerId: "minimax",
      api: "anthropic-messages",
      baseUrl: "https://api.minimax.io/anthropic",
      models: [
        { id: "MiniMax-M3", name: "MiniMax M3" },
        { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
        { id: "MiniMax-M2.7-highspeed", name: "MiniMax M2.7 Highspeed" },
      ],
      notes: "MiniMax 国际站;M3 支持思考开关,M2.7 始终 thinking。",
      category: "cn",
      websiteUrl: "https://platform.minimax.io",
    },
    {
      id: "stepfun",
      name: "阶跃星辰",
      providerId: "stepfun",
      api: "anthropic-messages",
      baseUrl: "https://api.stepfun.com/step_plan",
      models: [{ id: "step-3.5-flash-2603", name: "Step 3.5 Flash" }],
      notes: "StepFun Step Plan",
      category: "cn",
      websiteUrl: "https://platform.stepfun.com",
    },
    {
      id: "longcat",
      name: "LongCat",
      providerId: "longcat",
      api: "anthropic-messages",
      baseUrl: "https://api.longcat.chat/anthropic",
      models: [{ id: "LongCat-2.0", name: "LongCat 2.0" }],
      notes: "LongCat Anthropic 兼容",
      category: "cn",
      websiteUrl: "https://longcat.chat/platform",
    },
    {
      id: "xiaomi-mimo",
      name: "小米 MiMo",
      providerId: "xiaomi-mimo",
      api: "anthropic-messages",
      baseUrl: "https://api.xiaomimimo.com/anthropic",
      models: [{ id: "mimo-v2-flash", name: "MiMo V2 Flash" }],
      notes: "小米 MiMo Anthropic 兼容",
      category: "cn",
      websiteUrl: "https://platform.xiaomimimo.com",
    },
    {
      id: "doubao",
      name: "豆包 Seed",
      providerId: "doubao",
      api: "anthropic-messages",
      baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
      models: [{ id: "doubao-seed-1-8-251228", name: "Doubao Seed" }],
      notes: "火山方舟兼容端点",
      category: "cn",
      websiteUrl: "https://console.volcengine.com/ark",
    },
    {
      id: "bailing",
      name: "百灵",
      providerId: "bailing",
      api: "anthropic-messages",
      baseUrl: "https://api.tbox.cn/api/anthropic",
      models: [{ id: "Ling-1T", name: "Ling-1T" }],
      notes: "BaiLing Anthropic 兼容",
      category: "cn",
      websiteUrl: "https://tbox.cn",
    },
    {
      id: "qianfan-coding",
      name: "百度千帆 Coding",
      providerId: "qianfan",
      api: "anthropic-messages",
      baseUrl: "https://qianfan.baidubce.com/anthropic/coding",
      models: [{ id: "qianfan-code-latest", name: "Qianfan Code" }],
      notes: "百度千帆编程计划",
      category: "cn",
      websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
    },

    // —— 聚合 / 中转 ——
    {
      id: "siliconflow",
      name: "SiliconFlow",
      providerId: "siliconflow",
      api: "openai-completions",
      baseUrl: "https://api.siliconflow.cn/v1",
      models: [
        { id: "deepseek-ai/DeepSeek-V3", name: "DeepSeek V3" },
        { id: "Qwen/Qwen3-235B-A22B", name: "Qwen3 235B" },
      ],
      notes:
        "硅基流动 OpenAI 兼容。含 DeepSeek 模型时会写入 Pi deepseek compat（thinking / reasoning_content），因 baseUrl 非 api.deepseek.com。",
      category: "aggregator",
      websiteUrl: "https://cloud.siliconflow.cn",
    },
    {
      id: "siliconflow-en",
      name: "SiliconFlow (国际)",
      providerId: "siliconflow",
      api: "openai-completions",
      baseUrl: "https://api.siliconflow.com/v1",
      models: [{ id: "deepseek-ai/DeepSeek-V3", name: "DeepSeek V3" }],
      notes:
        "硅基流动国际站。DeepSeek 模型激活时自动写入 Pi deepseek compat。",
      category: "aggregator",
      websiteUrl: "https://cloud.siliconflow.com",
    },
    {
      id: "openrouter",
      name: "OpenRouter",
      providerId: "openrouter",
      api: "openai-completions",
      baseUrl: "https://openrouter.ai/api/v1",
      models: [
        { id: "anthropic/claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
        { id: "openai/gpt-4o", name: "GPT-4o" },
      ],
      notes: "OpenRouter 聚合路由",
      category: "aggregator",
      websiteUrl: "https://openrouter.ai",
    },
    {
      id: "opencode-go",
      name: "OpenCode Go",
      providerId: "opencode-go",
      // 主流开源模型（Grok / GLM / Kimi / DeepSeek / MiMo / Hy3）走 OpenAI 兼容端点。
      // MiniMax / Qwen 系列走 Anthropic 端点：api=anthropic-messages, baseUrl=https://opencode.ai/zen/go；
      // GPT-5.6 Luna 走 Responses：api=openai-responses, baseUrl=https://opencode.ai/zen/go。
      api: "openai-completions",
      baseUrl: "https://opencode.ai/zen/go/v1",
      models: [
        { id: "grok-4.5", name: "Grok 4.5" },
        { id: "glm-5.2", name: "GLM-5.2" },
        { id: "glm-5.1", name: "GLM-5.1" },
        { id: "kimi-k3", name: "Kimi K3" },
        { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
        { id: "kimi-k2.6", name: "Kimi K2.6" },
        { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
        { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
        { id: "mimo-v2.5", name: "MiMo-V2.5" },
        { id: "mimo-v2.5-pro", name: "MiMo-V2.5-Pro" },
        { id: "hy3", name: "Hy3" },
      ],
      notes:
        "OpenCode Go 订阅（opencode.ai/auth 领取 API Key，首月 $5 后 $10/月，含用量限额）。OpenAI 兼容端点为 /zen/go/v1/chat/completions；需 MiniMax / Qwen 模型时把 api 改为 anthropic-messages、baseUrl 改为 https://opencode.ai/zen/go；需 GPT-5.6 Luna 时改 api=openai-responses、同 baseUrl。模型列表见 https://opencode.ai/docs/zh-cn/go/",
      category: "aggregator",
      websiteUrl: "https://opencode.ai",
    },
    {
      id: "aihubmix",
      name: "AiHubMix",
      providerId: "aihubmix",
      api: "anthropic-messages",
      baseUrl: "https://aihubmix.com",
      models: [{ id: "claude-sonnet-4-5", name: "Claude Sonnet" }],
      notes: "AiHubMix 聚合",
      category: "aggregator",
      websiteUrl: "https://aihubmix.com",
    },
    {
      id: "dmxapi",
      name: "DMXAPI",
      providerId: "dmxapi",
      api: "anthropic-messages",
      baseUrl: "https://www.dmxapi.cn",
      models: [{ id: "claude-sonnet-4-5", name: "Claude Sonnet" }],
      notes: "DMXAPI 中转",
      category: "aggregator",
      websiteUrl: "https://www.dmxapi.cn",
    },
    {
      id: "modelscope",
      name: "ModelScope",
      providerId: "modelscope",
      api: "anthropic-messages",
      baseUrl: "https://api-inference.modelscope.cn",
      models: [{ id: "ZhipuAI/GLM-5.1", name: "GLM-5.1" }],
      notes: "魔搭社区推理",
      category: "aggregator",
      websiteUrl: "https://modelscope.cn",
    },
    {
      id: "novita",
      name: "Novita AI",
      providerId: "novita",
      api: "anthropic-messages",
      baseUrl: "https://api.novita.ai/anthropic",
      models: [{ id: "deepseek/deepseek-v3.2", name: "DeepSeek V3.2" }],
      notes: "Novita Anthropic 兼容",
      category: "aggregator",
      websiteUrl: "https://novita.ai",
    },
    {
      id: "nvidia",
      name: "NVIDIA NIM",
      providerId: "nvidia",
      api: "openai-completions",
      baseUrl: "https://integrate.api.nvidia.com/v1",
      models: [{ id: "meta/llama-3.1-70b-instruct", name: "Llama 3.1 70B" }],
      notes: "NVIDIA API catalog",
      category: "aggregator",
      websiteUrl: "https://build.nvidia.com",
    },
    {
      id: "packycode",
      name: "PackyCode",
      providerId: "packycode",
      api: "anthropic-messages",
      baseUrl: "https://www.packyapi.ai",
      models: [{ id: "claude-sonnet-4-5", name: "Claude Sonnet" }],
      notes: "PackyCode 中转",
      category: "aggregator",
      websiteUrl: "https://www.packyapi.ai",
    },

    // —— 官方 / 通用兼容 ——
    {
      id: "openai",
      name: "OpenAI",
      providerId: "openai",
      api: "openai-completions",
      baseUrl: "https://api.openai.com/v1",
      models: [
        { id: "gpt-4o", name: "GPT-4o" },
        { id: "gpt-4.1", name: "GPT-4.1" },
      ],
      notes: "OpenAI 官方",
      category: "official",
      websiteUrl: "https://platform.openai.com",
    },
    {
      id: "anthropic",
      name: "Anthropic",
      providerId: "anthropic",
      api: "anthropic-messages",
      baseUrl: "https://api.anthropic.com",
      models: [
        { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5" },
        { id: "claude-opus-4-5", name: "Claude Opus 4.5" },
      ],
      notes: "Anthropic 官方",
      category: "official",
      websiteUrl: "https://console.anthropic.com",
    },
    {
      id: "google",
      name: "Google Gemini",
      providerId: "google",
      api: "google-generative-ai",
      baseUrl: "https://generativelanguage.googleapis.com",
      models: [
        { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
        { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
      ],
      notes: "Google Generative AI",
      category: "official",
      websiteUrl: "https://aistudio.google.com",
    },
    {
      id: "openai-compatible",
      name: "OpenAI Compatible",
      providerId: "openai-compatible",
      api: "openai-completions",
      baseUrl: "https://api.openai.com/v1",
      models: [{ id: "gpt-4o", name: "GPT-4o" }],
      notes: "通用 OpenAI Chat Completions 兼容网关",
      category: "compatible",
    },
    {
      id: "anthropic-compatible",
      name: "Anthropic Compatible",
      providerId: "anthropic",
      api: "anthropic-messages",
      baseUrl: "https://api.anthropic.com",
      models: [{ id: "claude-sonnet-4-5", name: "Claude Sonnet" }],
      notes: "Anthropic Messages / 兼容中转",
      category: "compatible",
    },
    {
      id: "custom",
      name: "自定义空白",
      providerId: "custom",
      api: "openai-completions",
      baseUrl: "https://example.com/v1",
      models: [{ id: "my-model" }],
      notes: "自行填写 endpoint 与模型",
      category: "custom",
    },
  ];
}
