/**
 * Offline unit tests for godot-docs cache helpers + keyword search.
 * Does not clone the full repo (uses a tiny fixture tree).
 */
import {
  existsSync,
  mkdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import {
  docsSiteVersionForBranch,
  docsUrlForRst,
  getDocsDownloadZipUrl,
  getDocsRoot,
  isDocsUsefulBranch,
  normalizeGodotDocsBranch,
  sortDocsBranches,
} from "../electron/agent/godot-docs-cache";
import { searchGodotDocs } from "../electron/agent/godot-docs-search";

function assert(cond: boolean, msg: string): void {
  if (!cond) throw new Error(msg);
}

// --- branch helpers ---
assert(normalizeGodotDocsBranch("stable") === "stable", "stable ok");
assert(normalizeGodotDocsBranch(" master ") === "master", "trim ok");
assert(normalizeGodotDocsBranch("../evil") === "stable", "reject path");
assert(normalizeGodotDocsBranch("") === "stable", "empty → stable");
assert(normalizeGodotDocsBranch("3.6") === "3.6", "3.6 ok");
assert(docsSiteVersionForBranch("master") === "latest", "master → latest");
assert(docsSiteVersionForBranch("stable") === "stable", "stable site");
assert(
  getDocsDownloadZipUrl("4.7") ===
    "https://github.com/godotengine/godot-docs/archive/refs/heads/4.7.zip",
  "download zip url",
);
assert(
  docsUrlForRst("stable", "./classes/class_node.rst") ===
    "https://docs.godotengine.org/en/stable/classes/class_node.html",
  "strip ./ in url",
);
assert(
  docsUrlForRst("master", "tutorials/scripting/index.rst") ===
    "https://docs.godotengine.org/en/latest/tutorials/scripting.html",
  "index strip + latest",
);

assert(isDocsUsefulBranch("4.7"), "4.7 useful");
assert(isDocsUsefulBranch("stable"), "stable useful");
assert(!isDocsUsefulBranch("classref/sync-c12e519"), "reject classref");
assert(!isDocsUsefulBranch("feature/foo"), "reject feature");
const sorted = sortDocsBranches([
  "4.5",
  "classref/sync-ab6c6ee",
  "3.6",
  "master",
  "4.7",
  "stable",
]);
assert(
  sorted.join(",") === "stable,master,4.7,4.5,3.6",
  `sort order: ${sorted.join(",")}`,
);

// --- fixture search ---
const branch = "xagent-test";
const root = getDocsRoot(branch);
if (existsSync(root)) {
  rmSync(root, { recursive: true, force: true });
}
mkdirSync(join(root, "classes"), { recursive: true });
mkdirSync(join(root, "tutorials"), { recursive: true });
mkdirSync(join(root, "getting_started", "step_by_step"), { recursive: true });
mkdirSync(join(root, "engine_details", "file_formats"), { recursive: true });
// Fake .git so status helpers treat it as ready if needed
mkdirSync(join(root, ".git"), { recursive: true });

writeFileSync(
  join(root, "index.rst"),
  `Godot Docs Test
===============

Welcome.
`,
  "utf8",
);

writeFileSync(
  join(root, "classes", "class_characterbody2d.rst"),
  `CharacterBody2D
===============

.. _class_CharacterBody2D:

The CharacterBody2D node provides move_and_slide for 2D physics characters.

Methods
-------

* move_and_slide()
`,
  "utf8",
);

// Classref with Generated header — session regression for AnimationPlayer
writeFileSync(
  join(root, "classes", "class_animationplayer.rst"),
  `:github_url: hide

.. DO NOT EDIT THIS FILE!!!
.. Generated automatically from Godot engine sources.
.. Generator: https://github.com/godotengine/godot/tree/master/doc/tools/make_rst.py.
.. XML source: https://github.com/godotengine/godot/tree/master/doc/classes/AnimationPlayer.xml.

.. _class_AnimationPlayer:

AnimationPlayer
===============

**Inherits:** :ref:\`AnimationMixer<class_AnimationMixer>\`

A node used for animation playback.

.. rst-class:: classref-introduction-group

Description
-----------

An animation player is used for general-purpose playback of animations.

Signals
-------

.. _class_AnimationPlayer_signal_animation_finished:

* animation_finished
`,
  "utf8",
);

// Unrelated class whose Signals section mentions "signal" — must not beat tutorials
writeFileSync(
  join(root, "classes", "class_animatedsprite2d.rst"),
  `AnimatedSprite2D
================

.. Generated automatically from Godot engine sources.

A sprite that plays frame animations.

Description
-----------

SpriteFrames-driven 2D animation node.

Signals
-------

.. _class_AnimatedSprite2D_signal_animation_changed:

Emitted when the animation changes. Uses a signal callback.
`,
  "utf8",
);

writeFileSync(
  join(root, "getting_started", "step_by_step", "signals.rst"),
  `Using signals
=============

In this lesson, we will look at signals. They are messages that nodes emit when
something specific happens to them, like a button being pressed.
`,
  "utf8",
);

writeFileSync(
  join(root, "tutorials", "signals.rst"),
  `Using signals
=============

Connect a signal with connect() or the editor.
`,
  "utf8",
);

writeFileSync(
  join(root, "tutorials", "data_preferences.rst"),
  `AnimatedTexture vs. AnimatedSprite2D vs. AnimationPlayer vs. AnimationTree
=========================================================================

When comparing AnimationPlayer with AnimatedSprite2D, prefer the right node.
`,
  "utf8",
);

writeFileSync(
  join(root, "engine_details", "file_formats", "tscn.rst"),
  `TSCN format
===========

The :ref:\`class_AnimationPlayer\` node works with animation libraries.
`,
  "utf8",
);

const result = await searchGodotDocs({
  query: "move_and_slide",
  branch,
  limit: 5,
  autoEnsure: false,
});

assert(result.ok, `search ok: ${result.error ?? ""}`);
assert(result.branch === branch, "branch echoed");
assert(result.hits.length >= 1, "at least one hit");
assert(
  result.hits.some((h) => h.relPath.includes("class_characterbody2d")),
  "hit class file",
);
assert(
  result.hits.every((h) => h.absPath && !h.relPath.startsWith("./")),
  "absPath set and relPath normalized",
);
assert(
  result.hits.every((h) => typeof h.summary === "string"),
  "summary field present",
);
assert(
  result.hits[0]!.docsUrl.includes("xagent-test") &&
    !result.hits[0]!.docsUrl.includes("/./"),
  "docsUrl uses branch without ./",
);

const filtered = await searchGodotDocs({
  query: "signal",
  branch,
  pathGlob: "tutorials/*",
  autoEnsure: false,
});
assert(filtered.ok, "filtered search ok");
assert(
  filtered.hits.every((h) => h.relPath.startsWith("tutorials/")),
  "path_glob respected",
);

const empty = await searchGodotDocs({
  query: "zzzz-not-a-real-term-zzzz",
  branch,
  autoEnsure: false,
});
assert(empty.ok, "empty search still ok");
assert(empty.hits.length === 0, "no false hits");

// --- session regressions ---
const anim = await searchGodotDocs({
  query: "AnimationPlayer",
  branch,
  limit: 6,
  autoEnsure: false,
});
assert(anim.ok, `AnimationPlayer search ok: ${anim.error ?? ""}`);
assert(anim.hits.length >= 1, "AnimationPlayer has hits");
assert(
  anim.hits[0]!.relPath === "classes/class_animationplayer.rst",
  `AnimationPlayer #1 should be class page, got ${anim.hits[0]!.relPath}`,
);
assert(
  anim.hits[0]!.title === "AnimationPlayer",
  `AnimationPlayer title should be class name, got ${anim.hits[0]!.title}`,
);
assert(
  /playback of animations|animation playback/i.test(anim.hits[0]!.snippet) ||
    /playback of animations|animation playback/i.test(anim.hits[0]!.summary),
  "AnimationPlayer snippet/summary should include Description prose",
);
assert(
  !/Generated automatically/i.test(anim.hits[0]!.snippet),
  "AnimationPlayer snippet must not be generator boilerplate",
);

const signalHits = await searchGodotDocs({
  query: "signal",
  branch,
  limit: 6,
  autoEnsure: false,
});
assert(signalHits.ok, "signal search ok");
assert(signalHits.hits.length >= 1, "signal has hits");
const topSignal = signalHits.hits.slice(0, 3);
assert(
  topSignal.some(
    (h) =>
      h.relPath.includes("getting_started/") ||
      h.relPath.includes("tutorials/"),
  ),
  "signal top hits should include tutorial/getting_started",
);
assert(
  !topSignal.some(
    (h) =>
      h.relPath.includes("class_animatedsprite2d") &&
      /^signals$/i.test(h.title),
  ),
  "signal top hits must not be unrelated class Signals section titled Signals",
);
for (const h of signalHits.hits) {
  if (h.relPath.includes("class_animatedsprite2d")) {
    assert(
      h.title !== "Signals",
      "classref hit title should be page title, not Signals",
    );
  }
}

// cleanup
rmSync(root, { recursive: true, force: true });

console.log("test-godot-docs: ok");
